### ISSUE TITLE
None SAML backend entities must to be eduGAIN complient at the frontend metadata.

### ISSUE THREAD

**Issue by surfnet-niels** [its-dirg/vopaas_ansible#4]
If we connect a none saml entityto the back of our proxy, we still need to be saml and edugain compliment at our fronted for this entity. 
Therefore we e.g. must support contact data for the google endpoint at our frontend proxy.
Also see https://github.com/its-dirg/vopaas_ansible/issues/3

**Comment by rebeckag** [comment]
Contact info, etc. can be supplied under 'entity_info' for non-SAML backends, see e.g. [Google config example](https://github.com/its-dirg/SATOSA/blob/master/example/plugins/backends/google_backend.yaml.example#L15). This info will be included to the generated SAML metadata.
